services:
  virtual-dvr-recorder:
    image: alisonsalmeida/digital-dvr-recorder:latest
    container_name: virtual_dvr_recorder
    depends_on:
      - virtual-dvr-database
      - virtual-dvr-storage
      - virtual-dvr-live
    networks:
      - virtual-dvr-network
    restart: "always"
    env_file:
      - ".env"

  virtual-dvr-database:
    image: postgres:15-alpine
    container_name: virtual_dvr_database
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=dvr_user
      - POSTGRES_PASSWORD=dvr_pass
      - POSTGRES_DB=VIRTUAL_DVR
    restart: "always"
    volumes:
      - "/var/virtual-dvr-data:/var/lib/postgresql/data"
    networks:
      - virtual-dvr-network

  virtual-dvr-storage:
    image: minio/minio:latest
    container_name: virtual_dvr_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=dvr_user
      - MINIO_ROOT_PASSWORD=dvr_pass
      - MINIO_SERVER_URL=http://192.168.1.111:9000
    networks:
      - virtual-dvr-network
    volumes:
      - 'minio-storage:/data'
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    restart: "always"

  virtual-dvr-live:
    image: ossrs/srs:5
    container_name: virtual_dvr_live
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP
      - "1985:1985"   # HTTP API
      - "8080:8080"   # HTTP Server / HLS / Console
      - "8000:8000/udp" # WebRTC
    environment:
      - CANDIDATE=192.168.1.111
    command: ./objs/srs -c conf/rtmp2rtc.conf

networks:
  virtual-dvr-network:
    external: true

volumes:
  minio-storage:
    external: true
